language: node_js

node_js:
  - 6

branches:
  only:
    - master
    - testing
    - develop
    - stage

env:
  - FIREBASE_API_KEY=AIzaSyA3x4fZK6XJKXc6AlYShvgTqWskDTBLCh4 FIREBASE_AUTH_DOMAIN=storysimple-codydevstagemirror.firebaseapp.com FIREBASE_DATABASE_URL=https://storysimple-codydevstagemirror.firebaseio.com FIREBASE_STORAGE_BUCKET=storysimple-codydevstagemirror.appspot.com FIREBASE_MESSAGING_SENDER_ID=308562053467 NODE_ENV='production'

before_script:
  - npm install -g firebase-tools
  - npm install

script:
  - npm run test
  - npm run build

notifications:
  email:
    on_failure: change

cache:
  yarn: true
  directories:
    - node_modules

after_success:
  # - firebase use testing
  # - firebase deploy --token $FIREBASE_TOKEN
